apiVersion: v1
kind: Service
metadata:
  name: axum-java-executor
spec:
  selector:
    app: axum-java-executor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
